events {}
http {
 server {
 listen 80;
 location / {
 proxy_pass http://web-app:3000;
 }
 location /api/users {
 proxy_pass http://user-service:4000;
 }
 location /api/products {
 proxy_pass http://product-service:5000;
 }
 }
}